version: "3"
services:
# ahora se indican los servicios por el orden en que se quiere que se inicien. 

#Por ejemplo, mongo debe estar antes de order.
#mongo: mismo nombre usado en el run.sh de Order y application.properties.
#Se resuelve en una dirección IP.
  mongo: 
    image: paberlo/p1gps:db
    deploy:
      replicas: 1 # para escabilidad del servicio. 
      resources:
        limits:
          cpus: "0.2"
        #  memoryInGB: '0.2'
      restart_policy:
        condition: on-failure #reinicar el contenedor si falla
    ports:
      - "28017" 
      - "27017"
#      - "28017:28017" 
#      - "27017:27017"
    volumes:
      - "db-data:/data/db" # para dar persistencia a la sesión
  order:
    image: paberlo/p1gps:order
    depends_on:
#le pasamos al servicio order la IP del servicio mongo
      - "mongo" 
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          #memoryInGb: "0.5"
      restart_policy:
        condition: on-failure
    ports:
      - "8080"
#      - "8080:8080"
  web:
    image: paberlo/p1gps:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          #memoryInGb: "0.3"
      restart_policy:
        condition: on-failure
    ports:
       - "8080"
#      - "80:8080"  
  
#volumes: 
#   db-data:
volumes:
  db-data:
    driver: azure_file
    driver_opts:
      share_name: db-data
      storage_account_name: almacengps
